name: Run Tests

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:   # manual run button

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore -c Release

      - name: Build tests
        run: dotnet build CICDWASM.Tests/CICDWASM.Tests.csproj -c Release

      - name: Run tests
        run: |
            dotnet test CICDWASM.Tests/CICDWASM.Tests.csproj \
            --no-build \
            -c Release \
            --logger "trx" \
            --results-directory ./CICDWASM/TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./CICDWASM/TestResults/**/*.trx

      - name: Find TRX files
        run: find . -name "*.trx"

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests
          path: ./CICDWASM/TestResults/**/*.trx
          reporter: dotnet-trx